piggly:
  adapter: postgresql
  database: <%= ENV['PGDATABASE'] || 'piggly' %>
  username: <%= ENV['PGUSER']     || 'piggly' %>
  password: <%= ENV['PGPASSWORD'] || 'secret' %>
  host:     <%= ENV['PGHOST']     || 'localhost' %>
  port:     <%= ENV['PGPORT']     || 5432 %>
